achamber_web/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('change_pw/', views.AccountsChangePassword, name='change_pw'),
]

achamber_web/achamber_web/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('', include('status.urls')),
    path('accounts/', include('accounts.urls')),
    path('config/', include('config.urls')),
    path('monitor/', include('monitor.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

achamber_web/config/urls.py
from django.urls import path
from django.conf.urls import include
from config import views

urlpatterns = [
    path('', views.ConfigRequest, name='config-request'),
    path('watering/', views.WateringRequest, name='watering-request'),
]

achamber_web/monitor/urls.py
from django.urls import path
from django.conf.urls import include
from monitor import views

urlpatterns = [
    path('', views.MonitorGraph, name='monitor-graph'),
    path('delete_all/', views.DeleteAllMonitorData, name='delete-all'),
]

achamber_web/status/urls.py
from django.urls import path
from django.conf.urls import include
from status import views

urlpatterns = [
    path('', views.index, name='index'),
]

achamber_web/accounts/models.py
from django.db import models

# Create your models here.

achamber_web/config/models.py
from unittest.util import _MAX_LENGTH
from django.db import models

class ConfigTbl(models.Model):
    key = models.CharField(max_length=64, primary_key=True)
    value = models.CharField(max_length=64)
    
    def __str__(self):
        return f'{self.key} {self.value}'

achamber_web/monitor/models.py
from django.db import models

class Monitor(models.Model):
    date = models.CharField(max_length=21, null=False, blank=False)
    temperature = models.IntegerField(null=False, blank=False)
    hummidity = models.IntegerField(null=False, blank=False)
    
    def __str__(self):
        return f'{self.date} {self.temperature} {self.hummidity}'


class Event(models.Model):
    date = models.CharField(max_length=21, null=False, blank=False)
    humidifier_event = models.BooleanField(default=False)
    fan_event = models.BooleanField(default=False)
    pump_event = models.BooleanField(default=False)
    water_level_event = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.date} {self.humidifier_event} {self.fan_event} {self.pump_event} {self.water_level_event}'

achamber_web/status/models.py
from django.db import models

class Status(models.Model):
    name = models.CharField(max_length=64, primary_key=True)
    value = models.CharField(max_length=64)
    
    def __str__(self):
        return f'{self.name} {self.value}'

achamber_web/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.hashers import check_password
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.contrib import messages, auth
from django.http import HttpResponseRedirect
from django.urls import reverse

@login_required
def AccountsChangePassword(request):
    if request.method == "POST":
        user = request.user
        origin_password = request.POST.get('origin_password')
        if check_password(origin_password, user.password):
            new_password = request.POST.get('new_password')
            confirm_password = request.POST.get('confirm_password')
            if new_password == confirm_password:
                user.set_password(new_password)
                user.save()
                auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                return HttpResponseRedirect(reverse('index'))
            else:
                messages.error(request, 'Password not same')
        else:
            messages.error(request, 'Password not correct')
        return render(request, 'change_password.html')
    else:
        return render(request, 'change_password.html')

achamber_web/config/views.py
from multiprocessing import context
from django.shortcuts import render
from django.contrib.auth.decorators import permission_required, login_required
from config.models import ConfigTbl
from monitor.models import Monitor

@login_required
def ConfigRequest(request):
    context = {
    }
    config_list = ConfigTbl.objects.all()
    if (request.method == 'POST'):
        for config in config_list:
            value = request.POST.get(config.key)
            config.value = value
            config.save()
        context['result'] = 'Successfully configurations stored'
        
    config_list = ConfigTbl.objects.all().order_by('key')        
    context['config_list'] = config_list
    
    monitor_list = Monitor.objects.all().order_by('date')
    context['monitor_list'] = monitor_list
    
    return render(request, 'config_request.html', context=context)

@login_required
def WateringRequest(request):
    context = {
    }

    if (request.method == 'POST'):
        watering = request.POST.get('watering')
        enforce_watering = ConfigTbl.objects.get(pk='enforce watering')
        if (watering == 'on'):
            enforce_watering.value = '1'
        else:
            enforce_watering.value = '0'
        enforce_watering.save()

    enforce_watering = ConfigTbl.objects.get(pk='enforce watering')
    context['enforce_watering'] = enforce_watering

    return render(request, 'watering.html', context=context)

achamber_web/monitor/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import permission_required, login_required
from monitor.models import Monitor, Event

@login_required
def MonitorGraph(request):
    monitor_list = Monitor.objects.all().order_by('date')
    event_list = Event.objects.all().order_by('date')

    context = {
        'monitor_list'          : monitor_list,
        'event_list'            : event_list,
    }
    
    return render(request, 'monitor_graph.html', context=context)

def DeleteAllMonitorData(request):
    Monitor.objects.all().delete()
    Event.objects.all().delete()

    context = {
    }
    
    return render(request, 'monitor_graph.html', context=context)

achamber_web/status/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import permission_required, login_required

from status.models import Status
from config.models import ConfigTbl

@login_required
def index(request):
    if (request.method == 'POST'):
        is_run = request.POST.get('is_run')
        config_run = ConfigTbl.objects.get(pk='Operate chamber(0 - stop, 1 - run)')
        if (is_run == 'on'):
            config_run.value = '1'
        else:
            config_run.value = '0'
        config_run.save()

    status_run = Status.objects.get(pk='run')
    status_start_time = Status.objects.get(pk='start_time')
    status_end_time = Status.objects.get(pk='end_time')
    config_run = ConfigTbl.objects.get(pk='Operate chamber(0 - stop, 1 - run)')
    
    context = {
        'status_run'            : status_run,
        'status_start_time'     : status_start_time,
        'status_end_time'       : status_end_time,
        'config_run'            : config_run,
    }

    return render(request, 'index.html', context=context)

achamber_web/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>PCB Tools</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="/static/admin/css/base.css">
  <link rel="stylesheet" href="/static/admin/css/dark_mode.css">
  <link rel="stylesheet" href="/static/admin/css/nav_sidebar.css">
  <script src="/static/admin/js/nav_sidebar.js" defer></script>
  <link rel="stylesheet" href="/static/admin/css/changelists.css">
  <script src="/admin/jsi18n/"></script>
  <script src="/static/admin/js/vendor/jquery/jquery.js"></script>
  <script src="/static/admin/js/jquery.init.js"></script>
  <script src="/static/admin/js/core.js"></script>
  <script src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
  <script src="/static/admin/js/actions.js"></script>
  <script src="/static/admin/js/urlify.js"></script>
  <script src="/static/admin/js/prepopulate.js"></script>
  <script src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
  <script src="/static/admin/js/filters.js" defer></script>
  <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <link rel="stylesheet" href="/static/admin/css/responsive.css">
  <meta name="robots" content="NONE,NOARCHIVE">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  <link rel="stylesheet" href="/static/admin/css/toggle_switch.css">
  {% block head %}{% endblock %}
</head>
<body>
  <!-- 네비게이션바 -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}" style="color:#0d6aa8;">Hummidity Chamber</a>
      <button class="navbar-toggler" type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}  
            <a class="nav-link" href="{% url 'accounts:logout' %}">{{ user.last_name }}{{ user.first_name }} (Logout)</a>
          {% else %}
            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
          {% endif %}
          <a class="nav-link" href="{% url 'accounts:change_pw' %}">Change password</a>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'monitor-graph' %}">T/H Graph</a></li>
          <li><a href="{% url 'config-request' %}">Settings</a></li>
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

achamber_web/templates/change_password.html
{% extends "base_generic.html" %}

{% block content %}

  <div style="width=100%; height: 100px;">
  </div>
  <div style="width: 20%; height: 300px; float: left;">
  </div>
  <div class="container" style="width: 32%; height: auto; float: left; border-radius: 30px; border: 8px solid #ccff90; margin-right: 30px; margin-top: 0px; padding: 10px;">
    <form method="POST" action="{% url 'accounts:change_pw' %}">
      {% csrf_token %}
      <table>
        <tr>
          <th>Current password</th>
          <td><input name="origin_password" type="password"></td>
        </tr>
        <tr>
          <th>New password</th>
          <td><input name="new_password" type="password"></td>
        </tr>
        <tr>
          <th>Confirm password</th>
          <td><input name="confirm_password" type="password"></td>
        </tr>
        <tr>
          <td colspan="2" align="center"><input class="btn btn-primary" type="submit" value="변경"></td>
        </tr>
      </table>
    </form>
  </div>
  <div style="width: 10%; float: left; height: 300px;">
  </div>

{% endblock %}

achamber_web/templates/config_request.html
{% extends "base_generic.html" %}

{% block content %}
  {% load humanize %}

  <div style="width: auto; height: auto; float: left; border-radius: 30px; border: 8px solid #ccff90; padding: 10px; ">
    <div id="settings" style="white-space:nowrap; overflow:auto; width: auto;">
      <form action="{% url 'config-request' %}" method="POST" id="search">
        {% csrf_token %}
        <table id="purchase_list" style="width: 450px;">
          {% if result %}
          <tr>
            <td colspan="2" style="text-align: center; color: blue;">{{ result }}</td>
          </tr>
          {% endif %}
          {% for config in config_list %}
          <tr>
            <th>{{ config.key }}</th><td><input type="text" name="{{ config.key }}" value="{{ config.value }}"/></td>
          </tr>
          {% endfor %}
          <tr>
            <td colspan="2" align="center"><input type="submit" name="config" value="Apply"/></td>
          </tr>
        </table>
      </form>
    </div>
  </div>
{% endblock %}

achamber_web/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

achamber_web/templates/index.html
{% extends "base_generic.html" %}

{% block head %}
{% if config_run.value != status_run.value %}
  <meta http-equiv="refresh" content="1; url={% url 'index' %}">
{% endif %}
{% endblock %}

{% block content %}
  {% load humanize %}
  <div class="home" style="width: 1200px; height: 700px; vertical-align: middle;">
    <div class="operation" style="width: auto; height: auto; float: left; border-radius: 30px; border: 8px solid #ffcc80; white-space:nowrap; padding: 30px;">
      <form action="{% url 'index' %}" method="POST" id="operation">
        {% csrf_token %}
        <p style="text-align: center;">
        <label class="toggleSwitch xlarge" onclick="">
              <input type="checkbox" name="is_run" onchange="this.form.submit()" {% if config_run.value == '1' %}checked{% endif %} />
              <span>
                  <span>Stop</span>
                  <span>Running</span>
              </span>
              <a></a>
          </label>
      </p>
      {% if config_run.value == '1' %}
      <P style="text-align: center;"">
        <span style="font-size: 3.0em; color: #ff9800;"><strong>Start Time </strong></span>
        <span style="font-size: 2.5em; color: #0d6aa8;">{% if config_run.value == status_run.value %} {{ status_start_time.value }}{% else %}Wait to start...{% endif %}</span>
      </P>
      {% else %}
      <P style="text-align: center;">
        <span style="font-size: 3.0em; color: #ff9800;"><strong>Start Time </strong></span>
        <span style="font-size: 2.2em; color: #0d6aa8;"> {{ status_start_time.value }}</span>
      </P>
      <P style="text-align: center;">
        <span style="font-size: 3.0em; color: #ff9800;"><strong>End Time </strong></span>
        <span style="font-size: 2.2em; color: #0d6aa8;"> {% if config_run.value == status_run.value %}{{ status_end_time.value }}{% else %}Wait to stop...{% endif %}</span>
      </P>
      {% endif %}
      </form>
    </div>
    <div class="title-purchase-items" style="width: 20%; float: left; margin-right: 30px;">
    </div>
  </div>
{% endblock %}

achamber_web/templates/login.html
{% extends "base_generic.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'accounts:login' %}">
        {% csrf_token %}
        <table style="width: 100%; test-text_align: center;">
          <tr><td>
            <li style="font-size: 25px;">LOGIN</li>
          </tr></td>
        </table>
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">User ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">Password</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
</div>
{% endblock %}

achamber_web/templates/monitor_graph.html
{% extends "base_generic.html" %}

{% block content %}
  {% load humanize %}

  <div style="width: auto; height: auto; float: left; border-radius: 30px; border: 8px solid #ccff90; padding: 10px; ">
    <div>
	<li><a href="">Download data</a></li>
	<li><a href="{% url 'delete-all' %}">Delete All</a></li>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
      <canvas id="T/H Graph" width="1200" height="280"></canvas>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
      <canvas id="Humidifier Chart" width="1200" height="150"></canvas>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
      <canvas id="Fan Chart" width="1200" height="150"></canvas>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
      <canvas id="Pump Chart" width="1200" height="150"></canvas>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
      <canvas id="Water Level Chart" width="1200" height="150"></canvas>
    </div>
  </div>

  <script>
    new Chart(document.getElementById("T/H Graph"), {
      type: 'line',
      data: {
        labels: [
          {% for monitor in monitor_list%}"{{ monitor.date }}", {% endfor %}
        ],
        datasets: [
          { 
            data: [
              {% for monitor in monitor_list%}{{ monitor.temperature }}, {% endfor %}
            ],
            label: "Temperature",
            borderColor: "#e8c3b9",
            fill: false
          }, 
          { 
            data: [
              {% for monitor in monitor_list%}{{ monitor.hummidity }}, {% endfor %}
            ],
            label: "Hummidity",
            borderColor: "#c45850",
            fill: false
          }
        ]
      },
      options: {
        title: {
          display: true,
          text: 'Temperature and Hummidity'
        }
      }
    });

    new Chart(document.getElementById("Humidifier Chart"), {
      type: 'bar',
      data: {
        labels: [
          {% for event in event_list%}"{{ event.date }}", {% endfor %}
        ],
        datasets: [
          { 
            data: [
              {% for event in event_list%}{% if event.humidifier_event %}1, {% else %}0, {% endif %}{% endfor %}
            ],
            label: "On/Off",
            borderColor: "#e8c3b9",
            fill: false
          }, 
        ]
      },
      options: {
        title: {
          display: true,
          text: 'Humidifier On/Off Chart'
        }
      }
    });

    new Chart(document.getElementById("Fan Chart"), {
      type: 'bar',
      data: {
        labels: [
          {% for event in event_list%}"{{ event.date }}", {% endfor %}
        ],
        datasets: [
          { 
            data: [
              {% for event in event_list%}{% if event.fan_event %}1, {% else %}0, {% endif %}{% endfor %}
            ],
            label: "On/Off",
            borderColor: "#e8c3b9",
            fill: false
          }, 
        ]
      },
      options: {
        title: {
          display: true,
          text: 'Fan On/Off Chart'
        }
      }
    });

    new Chart(document.getElementById("Pump Chart"), {
      type: 'bar',
      data: {
        labels: [
          {% for event in event_list%}"{{ event.date }}", {% endfor %}
        ],
        datasets: [
          { 
            data: [
              {% for event in event_list%}{% if event.pump_event %}1, {% else %}0, {% endif %}{% endfor %}
            ],
            label: "On/Off",
            borderColor: "#e8c3b9",
            fill: false
          }, 
        ]
      },
      options: {
        title: {
          display: true,
          text: 'Water Pump On/Off Chart'
        }
      }
    });

    new Chart(document.getElementById("Water Level Chart"), {
      type: 'bar',
      data: {
        labels: [
          {% for event in event_list%}"{{ event.date }}", {% endfor %}
        ],
        datasets: [
          { 
            data: [
              {% for event in event_list%}{% if event.water_level_event %}1, {% else %}0, {% endif %}{% endfor %}
            ],
            label: "On/Off",
            borderColor: "#e8c3b9",
            fill: false
          }, 
        ]
      },
      options: {
        title: {
          display: true,
          text: 'Water Level On/Off Chart'
        }
      }
    });
  </script>
{% endblock %}


achamber_web/templates/watering.html
{% extends "base_generic.html" %}

{% block head %}
{% if enforce_watering.value == '1' %}
  <meta http-equiv="refresh" content="1; url={% url 'watering-request' %}">
{% endif %}
{% endblock %}

{% block content %}
  {% load humanize %}
  <div class="home" style="width: 1200px; height: 700px; vertical-align: middle;">
    <div class="operation" style="width: auto; height: auto; float: left; border-radius: 30px; border: 8px solid #ffcc80; white-space:nowrap; padding: 30px;">
      <form action="{% url 'watering-request' %}" method="POST" id="watering">
        {% csrf_token %}
        <p style="text-align: center;">
        <label class="toggleSwitch xlarge" onclick="">
              <input type="checkbox" name="watering" onchange="this.form.submit()" {% if enforce_watering.value == '1' %}checked{% endif %} />
              <span>
                  <span>Stop</span>
                  <span>Watering</span>
              </span>
              <a></a>
          </label>
      </p>
      </form>
    </div>
  </div>
{% endblock %}